import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "nomu",
    description: "Generated by Hari-42",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className="bg-[#F1E5B1] text-green-800">
        {children}
        <footer className="bg-[#F1E5B1] w-full">
            <div className="max-w-screen-xl mx-auto p-4">
                <hr className="my-6 border-t-4  border-green-900" />
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-8 text-left">
                    <div>
                        <span className="text-2xl font-bold text-green-800">nomu</span>
                    </div>

                    <div>
                        <h2 className="mb-4 text-2xl font-bold text-green-800">Resources</h2>
                        <ul className="font-medium">
                            <li className="mb-2">
                                <a
                                    href="https://tailwindcss.com/"
                                    className="hover:text-green-500 text-green-800 font-semibold transition-colors duration-300"
                                >
                                    Tailwind CSS
                                </a>
                            </li>
                        </ul>
                    </div>

                    <div>
                        <h2 className="mb-4 text-2xl font-bold text-green-800">Socials</h2>
                        <ul className="font-medium">
                            <li className="mb-2">
                                <a
                                    href="https://github.com/Hari-42"
                                    className="hover:text-green-500 text-green-800 font-semibold transition-colors duration-300"
                                >
                                    Github - Hari-42
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <hr className="my-6 border-t-4  border-green-900" />
                <div className="flex items-center justify-center">
                    <span className="text-sm font-bold text-green-800">© 2025 nomu, All Rights Reserved.</span>
                </div>
            </div>
        </footer>


        </body>
        </html>
    );
}
