import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <header className="p-4 border-b shadow-sm bg-white">
            <nav className="flex space-x-4">
                <Link href="/" className="text-blue-600 hover:underline">
                    Home
                </Link>
                <Link href="/about" className="text-blue-600 hover:underline">
                    About
                </Link>
                <Link href="/products" className="text-blue-600 hover:underline">
                    Products
                </Link>
            </nav>
        </header>
        <main className="p-4">{children}</main>
        </body>
        </html>
    );
}
